import { useEffect, useRef, useState } from 'react';
import { Alert, FlatList, Image, KeyboardAvoidingView, Platform, Pressable, StyleSheet, View } from 'react-native';
import { Stack, useLocalSearchParams, useRouter } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { spacing } from '@/constants/theme';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/providers/AuthProvider';
import { useTheme } from '@/providers/ThemeProvider';
import type { Message } from '@/types';
import { ChatInput } from '@/components/ChatInput';
import { MessageBubble } from '@/components/MessageBubble';
import { LoadingState } from '@/components/Screen';
import { AppText } from '@/components/AppText';

export default function ChatScreen() {
  const { palette } = useTheme(); const { matchId, name } = useLocalSearchParams<{ matchId: string; name?: string }>(); const router = useRouter(); const { user } = useAuth(); const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [loading, setLoading] = useState(true); const [otherUserId, setOtherUserId] = useState<string | null>(null); const [otherName, setOtherName] = useState(name || 'საუბარი'); const [otherPhoto, setOtherPhoto] = useState<string | null>(null); const list = useRef<FlatList<Message>>(null);
  useEffect(() => { if (!matchId || !user) return; let mounted = true; (async () => { const [{ data: match }, { data: data }] = await Promise.all([supabase.from('matches').select('user1_id,user2_id').eq('id', matchId).maybeSingle(), supabase.from('messages').select('*').eq('match_id', matchId).is('deleted_at', null).order('created_at', { ascending: true })]); if (!mounted) return; const matchedUserId = match ? (match.user1_id === user.id ? match.user2_id : match.user1_id) : null; if (matchedUserId) { setOtherUserId(matchedUserId); const [{ data: matchedProfile }, { data: matchedPhoto }] = await Promise.all([supabase.from('profiles').select('first_name').eq('id', matchedUserId).maybeSingle(), supabase.from('photos').select('url').eq('user_id', matchedUserId).order('position', { ascending: true }).limit(1).maybeSingle()]); if (mounted) { if (matchedProfile?.first_name) setOtherName(matchedProfile.first_name); setOtherPhoto(matchedPhoto?.url || null); } } const unread = (data || []).filter((item) => !item.read && item.sender_id !== user.id).map((item) => item.id); if (unread.length) await supabase.from('messages').update({ read: true, read_at: new Date().toISOString() }).in('id', unread); setMessages((data || []).map((item) => unread.includes(item.id) ? { ...item, read: true } : item) as Message[]); setLoading(false); })(); const channel = supabase.channel(`mobile-chat-${matchId}`).on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages', filter: `match_id=eq.${matchId}` }, async (payload) => { const message = payload.new as Message; if (message.sender_id !== user.id && !message.read) await supabase.from('messages').update({ read: true, read_at: new Date().toISOString() }).eq('id', message.id); setMessages((current) => current.some((item) => item.id === message.id) ? current : [...current, { ...message, read: message.sender_id !== user.id ? true : message.read }]); }).subscribe(); return () => { mounted = false; void supabase.removeChannel(channel); }; }, [matchId, user]);
  async function send() { const content = input.trim(); if (!content || !user || !matchId) return; setInput(''); const { error } = await supabase.from('messages').insert({ match_id: matchId, sender_id: user.id, content }); if (error) { setInput(content); Alert.alert('ვერ გაიგზავნა', error.message); } }
  function report() { if (!user || !otherUserId) return; Alert.alert('მომხმარებლის დარეპორტება', 'გსურთ ამ მომხმარებლის დარეპორტება?', [{ text: 'გაუქმება', style: 'cancel' }, { text: 'დარეპორტება', style: 'destructive', onPress: async () => { const { error } = await supabase.from('reports').insert({ reporter_id: user.id, reported_id: otherUserId, reason: 'other', description: 'Reported from mobile chat' }); if (error) Alert.alert('ვერ მოხერხდა', error.message); else Alert.alert('გაიგზავნა', 'მადლობა შეტყობინებისთვის.'); } }]); }
  function block() { if (!user || !otherUserId || !matchId) return; Alert.alert('მომხმარებლის დაბლოკვა', 'დაბლოკვის შემდეგ ეს მატჩი წაიშლება.', [{ text: 'გაუქმება', style: 'cancel' }, { text: 'დაბლოკვა', style: 'destructive', onPress: async () => { const { error } = await supabase.from('blocks').insert({ blocker_id: user.id, blocked_id: otherUserId }); if (!error) await supabase.from('matches').delete().eq('id', matchId); if (error) Alert.alert('ვერ მოხერხდა', error.message); else router.back(); } }]); }
  function safetyMenu() { Alert.alert('უსაფრთხოება', 'აირჩიე მოქმედება', [{ text: 'დარეპორტება', onPress: report }, { text: 'დაბლოკვა', style: 'destructive', onPress: block }, { text: 'გაუქმება', style: 'cancel' }]); }
  if (loading) return <LoadingState />;
  return <KeyboardAvoidingView style={[styles.root, { backgroundColor: palette.paper }]} behavior={Platform.OS === 'ios' ? 'padding' : 'height'} keyboardVerticalOffset={Platform.OS === 'ios' ? 88 : 0}><Stack.Screen options={{ headerShown: true, title: otherName, headerTintColor: palette.rose, headerStyle: { backgroundColor: palette.paper }, headerTitleStyle: { color: palette.ink }, headerRight: () => <Pressable onPress={safetyMenu} hitSlop={10}><Ionicons name="ellipsis-horizontal" size={23} color={palette.rose} /></Pressable> }} /><View style={[styles.profileRow, { borderBottomColor: palette.line }]}>{otherPhoto ? <Image source={{ uri: otherPhoto }} style={styles.profilePhoto} /> : <View style={[styles.profileFallback, { backgroundColor: palette.roseSoft }]}><Ionicons name="person" size={20} color={palette.rose} /></View>}<AppText style={styles.profileName}>{otherName}</AppText></View><FlatList ref={list} data={messages} keyExtractor={(message) => message.id} keyboardShouldPersistTaps="handled" automaticallyAdjustKeyboardInsets contentContainerStyle={styles.list} renderItem={({ item }) => <MessageBubble message={item} own={item.sender_id === user?.id} />} onContentSizeChange={() => list.current?.scrollToEnd({ animated: false })} /><ChatInput value={input} onChangeText={setInput} onFocus={() => setTimeout(() => list.current?.scrollToEnd({ animated: true }), 80)} onSend={send} disabled={!input.trim()} /></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ root: { flex: 1 }, profileRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: spacing.md, paddingTop: 10, paddingBottom: 8, borderBottomWidth: 1 }, profilePhoto: { width: 42, height: 42, borderRadius: 21 }, profileFallback: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' }, profileName: { fontWeight: '700', fontSize: 16 }, list: { padding: spacing.md, paddingBottom: 20 } });
