import { useState } from 'react';
import { Alert, Image, Pressable, StyleSheet, TextInput as RNTextInput, View, type TextInputProps } from 'react-native';
import { useRouter } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { Ionicons } from '@expo/vector-icons';
import { colors, radius, spacing } from '@/constants/theme';
import { INTEREST_KEYS, INTEREST_LABELS } from '@/constants/interests';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/providers/AuthProvider';
import { AppText } from '@/components/AppText';
import { PrimaryButton } from '@/components/PrimaryButton';
import { Screen } from '@/components/Screen';
import { useLanguage } from '@/providers/LanguageProvider';

export default function OnboardingScreen() {
  const router = useRouter(); const { user, profile, refresh } = useAuth(); const { language } = useLanguage(); const [step, setStep] = useState(0); const [bio, setBio] = useState(profile?.bio || ''); const [photos, setPhotos] = useState<string[]>([]); const [selected, setSelected] = useState<string[]>([]); const [busy, setBusy] = useState(false);
  async function addPhotos() { if (!user) return; const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert('ფოტოებზე წვდომა საჭიროა'); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsMultipleSelection: true, selectionLimit: 6 - photos.length, quality: 0.86, allowsEditing: false }); if (!result.canceled) setPhotos((current) => [...current, ...result.assets.map((asset) => asset.uri)].slice(0, 6)); }
  async function finish() { if (!user || photos.length === 0 || selected.length < 3) return; setBusy(true); try { for (let index = 0; index < photos.length; index += 1) { const response = await fetch(photos[index]); const blob = await response.arrayBuffer(); const path = `${user.id}/${Date.now()}-${index}.jpg`; const upload = await supabase.storage.from('profile-photos').upload(path, blob, { contentType: 'image/jpeg', upsert: false }); if (upload.error) throw upload.error; const { data: urlData } = supabase.storage.from('profile-photos').getPublicUrl(path); const inserted = await supabase.from('photos').insert({ user_id: user.id, url: urlData.publicUrl, position: index }); if (inserted.error) throw inserted.error; } const interestRows = await supabase.from('interests').select('id, key').in('key', selected); if (interestRows.error) throw interestRows.error; if (interestRows.data?.length) { const links = await supabase.from('user_interests').insert(interestRows.data.map((item) => ({ user_id: user.id, interest_id: item.id }))); if (links.error) throw links.error; } const updated = await supabase.from('profiles').update({ bio: bio.trim(), profile_completed: true }).eq('id', user.id); if (updated.error) throw updated.error; await refresh(); router.replace('/(tabs)/discover'); } catch (error) { Alert.alert('პროფილის შექმნა ვერ მოხერხდა', error instanceof Error ? error.message : 'სცადე თავიდან.'); } finally { setBusy(false); } }
  const canContinue = step === 0 ? bio.trim().length > 0 : step === 1 ? photos.length > 0 : selected.length >= 3;
  return <Screen><View style={styles.progress}>{[0, 1, 2].map((item) => <View key={item} style={[styles.progressBar, item <= step && styles.progressActive]} />)}</View><AppText style={styles.step}>ნაბიჯი {step + 1} / 3</AppText><AppText style={styles.title}>{step === 0 ? 'მოგვიყევი შენზე' : step === 1 ? 'დაამატე ფოტოები' : 'აირჩიე ინტერესები'}</AppText><AppText style={styles.sub}>{step === 0 ? 'კარგი ბიო დაგეხმარება სწორი ადამიანების პოვნაში.' : step === 1 ? 'პირველი ფოტო შენი მთავარი პროფილის ფოტო იქნება.' : 'მონიშნე მინიმუმ 3 და მაქსიმუმ 8 ინტერესი.'}</AppText>{step === 0 && <TextInput value={bio} onChangeText={setBio} multiline maxLength={500} placeholder="დაწერე რამდენიმე სიტყვა შენს შესახებ..." placeholderTextColor={colors.muted} style={[styles.input, styles.bio]} />}{step === 1 && <><Pressable style={styles.upload} onPress={() => void addPhotos()}><Ionicons name="camera-outline" size={32} color={colors.rose} /><AppText style={styles.link}>ფოტოების არჩევა</AppText></Pressable><View style={styles.grid}>{photos.map((uri, index) => <View key={uri} style={styles.photoWrap}><Image source={{ uri }} style={styles.photo} /><Pressable onPress={() => setPhotos((current) => current.filter((_, item) => item !== index))} style={styles.remove}><Ionicons name="close" size={16} color={colors.white} /></Pressable></View>)}</View></>}{step === 2 && <View style={styles.interests}>{INTEREST_KEYS.map((key) => <Pressable key={key} onPress={() => setSelected((current) => current.includes(key) ? current.filter((item) => item !== key) : current.length < 8 ? [...current, key] : current)} style={[styles.chip, selected.includes(key) && styles.chipActive]}><AppText style={selected.includes(key) && styles.chipText}>{INTEREST_LABELS[key]}</AppText></Pressable>)}</View>}<View style={styles.actions}>{step > 0 && <PrimaryButton title="უკან" variant="ghost" onPress={() => setStep((current) => current - 1)} />}{step < 2 ? <PrimaryButton title="გაგრძელება" disabled={!canContinue} onPress={() => setStep((current) => current + 1)} /> : <PrimaryButton title="დასრულება" loading={busy} disabled={!canContinue} onPress={() => void finish()} />}</View></Screen>;
}

function TextInput(props: TextInputProps) { const { language } = useLanguage(); const placeholder = language === 'en' && props.placeholder === 'დაწერე რამდენიმე სიტყვა შენს შესახებ...' ? 'Write a few words about yourself...' : props.placeholder; return <RNTextInput {...props} placeholder={placeholder} />; }

const styles = StyleSheet.create({ progress: { flexDirection: 'row', gap: 6, marginBottom: 8 }, progressBar: { flex: 1, height: 5, borderRadius: 3, backgroundColor: colors.line }, progressActive: { backgroundColor: colors.rose }, step: { color: colors.muted, fontSize: 12 }, title: { fontSize: 30, fontWeight: '800', marginTop: spacing.lg }, sub: { color: colors.muted, lineHeight: 22, marginTop: 8, marginBottom: spacing.lg }, input: { borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, padding: 15, color: colors.ink, backgroundColor: colors.surface }, bio: { minHeight: 150, textAlignVertical: 'top' }, upload: { minHeight: 150, borderWidth: 2, borderStyle: 'dashed', borderColor: colors.line, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', gap: 8 }, link: { color: colors.rose, fontWeight: '700' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 14 }, photoWrap: { width: '31.8%', aspectRatio: 1, borderRadius: radius.sm, overflow: 'hidden' }, photo: { width: '100%', height: '100%' }, remove: { position: 'absolute', right: 4, top: 4, width: 24, height: 24, borderRadius: 12, backgroundColor: 'rgba(0,0,0,0.6)', alignItems: 'center', justifyContent: 'center' }, interests: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { paddingHorizontal: 13, paddingVertical: 9, borderRadius: radius.pill, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line }, chipActive: { backgroundColor: colors.rose, borderColor: colors.rose }, chipText: { color: colors.white }, actions: { flexDirection: 'row', justifyContent: 'space-between', gap: 12, marginTop: spacing.xl } });
