import { useState } from 'react';
import { Alert, Image, Pressable, StyleSheet, TextInput, View } from 'react-native';
import { Stack, useRouter } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { Ionicons } from '@expo/vector-icons';
import { colors, radius, spacing } from '@/constants/theme';
import { supabase } from '@/lib/supabase';
import { useAuth } from '@/providers/AuthProvider';
import { AppText } from '@/components/AppText';
import { PrimaryButton } from '@/components/PrimaryButton';
import { Screen } from '@/components/Screen';

export default function VerificationScreen() {
  const router = useRouter(); const { user, profile, refresh } = useAuth(); const [image, setImage] = useState<string | null>(null); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false); const status = profile?.verification_status || 'unverified';
  async function choosePhoto() { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) return Alert.alert('ფოტოებზე წვდომა საჭიროა'); const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [1, 1], quality: 0.9 }); if (!result.canceled && result.assets[0]) setImage(result.assets[0].uri); }
  async function submit() { if (!user || !image) return; setBusy(true); try { const response = await fetch(image); const blob = await response.arrayBuffer(); const path = `${user.id}/verification-${Date.now()}.jpg`; const upload = await supabase.storage.from('verification-photos').upload(path, blob, { contentType: 'image/jpeg', upsert: false }); if (upload.error) throw upload.error; const { data: urlData } = supabase.storage.from('verification-photos').getPublicUrl(path); const request = await supabase.from('verification_requests').insert({ user_id: user.id, selfie_photo_url: urlData.publicUrl, notes }); if (request.error) throw request.error; const update = await supabase.from('profiles').update({ verification_status: 'pending' }).eq('id', user.id); if (update.error) throw update.error; await refresh(); Alert.alert('მოთხოვნა გაიგზავნა', 'ვერიფიკაციას მალე განვიხილავთ.'); router.back(); } catch (error) { Alert.alert('ვერიფიკაცია ვერ მოხერხდა', error instanceof Error ? error.message : 'სცადე თავიდან.'); } finally { setBusy(false); } }
  return <><Stack.Screen options={{ headerShown: true, title: 'ვერიფიკაცია', headerTintColor: colors.rose }} /><Screen><View style={styles.status}><Ionicons name={status === 'verified' ? 'checkmark-circle' : status === 'pending' ? 'time' : status === 'rejected' ? 'close-circle' : 'shield-checkmark'} size={42} color={status === 'verified' ? colors.green : colors.rose} /><AppText style={styles.title}>{status === 'verified' ? 'პროფილი ვერიფიცირებულია' : status === 'pending' ? 'მოთხოვნა განხილვაშია' : status === 'rejected' ? 'მოთხოვნა უარყოფილია' : 'პროფილის ვერიფიკაცია'}</AppText><AppText style={styles.muted}>დაამატე სელფი, რომ დაადასტურო შენი პროფილი.</AppText></View>{status !== 'verified' && status !== 'pending' && <View style={styles.form}><Pressable onPress={choosePhoto} style={styles.upload}>{image ? <Image source={{ uri: image }} style={styles.preview} /> : <><Ionicons name="camera-outline" size={34} color={colors.rose} /><AppText style={styles.link}>სელფის არჩევა</AppText></>}</Pressable><TextInput value={notes} onChangeText={setNotes} placeholder="დამატებითი ინფორმაცია" placeholderTextColor={colors.muted} style={[styles.input, styles.notes]} multiline maxLength={500} /><PrimaryButton title="მოთხოვნის გაგზავნა" loading={busy} disabled={!image} onPress={submit} /></View>}</Screen></>;
}

const styles = StyleSheet.create({ status: { alignItems: 'center', padding: spacing.xl, backgroundColor: colors.surface, borderRadius: radius.md, gap: 9, marginBottom: spacing.lg }, title: { fontSize: 21, fontWeight: '800', textAlign: 'center' }, muted: { color: colors.muted, textAlign: 'center', lineHeight: 21 }, form: { gap: 13 }, upload: { minHeight: 190, borderWidth: 2, borderStyle: 'dashed', borderColor: colors.line, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', gap: 10 }, preview: { width: 140, height: 140, borderRadius: 70 }, link: { color: colors.rose, fontWeight: '700' }, input: { minHeight: 52, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, paddingHorizontal: 14, color: colors.ink, backgroundColor: colors.surface }, notes: { minHeight: 95, textAlignVertical: 'top', paddingTop: 13 } });
