import { useState } from 'react';
import { Keyboard, Pressable, StyleSheet, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { colors, radius, spacing } from '@/constants/theme';
import { useTheme } from '@/providers/ThemeProvider';
import { useLanguage } from '@/providers/LanguageProvider';

export function ChatInput({ value, onChangeText, onSend, disabled, onFocus }: { value: string; onChangeText: (value: string) => void; onSend: () => void; disabled?: boolean; onFocus?: () => void }) { const { palette } = useTheme(); const { language } = useLanguage(); const [focused, setFocused] = useState(false); return <View style={{ backgroundColor: palette.paper }}>{focused && <Pressable accessibilityLabel={language === 'en' ? 'Dismiss keyboard' : 'კლავიატურის დახურვა'} onPress={() => { Keyboard.dismiss(); setFocused(false); }} style={[styles.dismiss, { borderBottomColor: palette.line }]}><Ionicons name="chevron-down" size={19} color={palette.muted} /></Pressable>}<View style={[styles.row, { borderTopColor: palette.line, backgroundColor: palette.paper }]}><TextInput value={value} onChangeText={onChangeText} onFocus={() => { setFocused(true); onFocus?.(); }} onBlur={() => setFocused(false)} placeholder={language === 'en' ? 'Write a message...' : 'დაწერე შეტყობინება...'} placeholderTextColor={palette.muted} style={[styles.input, { backgroundColor: palette.surface, borderColor: palette.line, color: palette.ink }]} multiline maxLength={1000} /><Pressable disabled={disabled} onPress={onSend} style={[styles.send, disabled && { opacity: 0.45 }]}><Ionicons name="arrow-up" color={colors.white} size={21} /></Pressable></View></View>; }
const styles = StyleSheet.create({ dismiss: { height: 30, alignItems: 'center', justifyContent: 'center', borderBottomWidth: 1 }, row: { flexDirection: 'row', alignItems: 'flex-end', gap: 8, padding: spacing.sm, borderTopWidth: 1, borderTopColor: colors.line, backgroundColor: colors.paper }, input: { flex: 1, maxHeight: 110, minHeight: 44, paddingHorizontal: 15, paddingVertical: 11, borderRadius: radius.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, color: colors.ink, fontSize: 15 }, send: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.rose, alignItems: 'center', justifyContent: 'center' } });
