import { useEffect, useState } from 'react';
import { Alert, Image, Pressable, StyleSheet, TextInput, View } from 'react-native';
import { useRouter } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { Ionicons } from '@expo/vector-icons';
import { colors, radius, spacing } from '@/constants/theme';
import { supabase } from '@/lib/supabase';
import { calculateAge, displayIntention } from '@/lib/helpers';
import { useAuth } from '@/providers/AuthProvider';
import type { Photo } from '@/types';
import { AppText } from '@/components/AppText';
import { PrimaryButton } from '@/components/PrimaryButton';
import { Screen } from '@/components/Screen';

export default function ProfileScreen() {
  const router = useRouter(); const { user, profile, refresh, signOut } = useAuth(); const [photos, setPhotos] = useState<Photo[]>([]); const [editing, setEditing] = useState(false); const [name, setName] = useState(''); const [bio, setBio] = useState(''); const [city, setCity] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (profile) { setName(profile.first_name); setBio(profile.bio); setCity(profile.city); } }, [profile]);
  useEffect(() => { if (user) void supabase.from('photos').select('*').eq('user_id', user.id).order('position').then(({ data }) => setPhotos((data || []) as Photo[])); }, [user]);
  if (!profile || !user) return null;
  const userId = user.id;
  async function save() { setSaving(true); const { error } = await supabase.from('profiles').update({ first_name: name.trim(), bio: bio.trim(), city: city.trim() }).eq('id', userId); setSaving(false); if (error) Alert.alert('ვერ მოხერხდა', error.message); else { await refresh(); setEditing(false); } }
  async function addPhoto() { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { Alert.alert('ფოტოებზე წვდომა საჭიროა'); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.86, allowsEditing: true, aspect: [1, 1] }); if (result.canceled || !result.assets[0]) return; const asset = result.assets[0]; const path = `${userId}/${Date.now()}.jpg`; const response = await fetch(asset.uri); const blob = await response.arrayBuffer(); const { error: uploadError } = await supabase.storage.from('profile-photos').upload(path, blob, { contentType: 'image/jpeg', upsert: false }); if (uploadError) { Alert.alert('ფოტოს ატვირთვა ვერ მოხერხდა', uploadError.message); return; } const { data: urlData } = supabase.storage.from('profile-photos').getPublicUrl(path); const { data, error } = await supabase.from('photos').insert({ user_id: userId, url: urlData.publicUrl, position: photos.length }).select().single(); if (error) Alert.alert('ვერ მოხერხდა', error.message); else if (data) setPhotos((current) => [...current, data as Photo]); }
  async function deletePhoto(photo: Photo) { await supabase.from('photos').delete().eq('id', photo.id); setPhotos((current) => current.filter((item) => item.id !== photo.id)); }
  return <Screen><View style={styles.header}><View><AppText style={styles.eyebrow}>ჩემი პროფილი</AppText><AppText style={styles.title}>{profile.first_name}</AppText></View><Pressable onPress={() => router.push('/settings')}><Ionicons name="settings-outline" size={24} color={colors.ink} /></Pressable></View><View style={styles.photoGrid}>{[...Array(6)].map((_, index) => { const photo = photos[index]; return <View key={index} style={styles.photoSlot}>{photo ? <><Image source={{ uri: photo.url }} style={styles.photo} />{editing && <Pressable onPress={() => deletePhoto(photo)} style={styles.delete}><Ionicons name="close" size={16} color={colors.white} /></Pressable>}</> : editing ? <Pressable onPress={addPhoto} style={styles.add}><Ionicons name="add" size={28} color={colors.rose} /></Pressable> : null}</View>; })}</View>{editing ? <View style={styles.form}><TextInput value={name} onChangeText={setName} style={styles.input} placeholder="სახელი" placeholderTextColor={colors.muted} /><TextInput value={city} onChangeText={setCity} style={styles.input} placeholder="ქალაქი" placeholderTextColor={colors.muted} /><TextInput value={bio} onChangeText={setBio} style={[styles.input, styles.bioInput]} placeholder="შენს შესახებ" placeholderTextColor={colors.muted} multiline /><PrimaryButton title="შენახვა" loading={saving} onPress={save} /><PrimaryButton title="გაუქმება" variant="ghost" onPress={() => setEditing(false)} /></View> : <><View style={styles.info}><View style={styles.nameRow}><AppText style={styles.profileName}>{profile.first_name}</AppText>{calculateAge(profile.date_of_birth) ? <AppText style={styles.profileAge}>{calculateAge(profile.date_of_birth)}</AppText> : null}{profile.is_verified && <Ionicons name="checkmark-circle" color={colors.rose} size={21} />}</View><AppText style={styles.muted}>{profile.city}{profile.relationship_intention ? ` · ${displayIntention(profile.relationship_intention)}` : ''}</AppText>{profile.bio ? <AppText style={styles.bio}>{profile.bio}</AppText> : null}</View><PrimaryButton title="პროფილის რედაქტირება" variant="soft" onPress={() => setEditing(true)} /></>}<Pressable onPress={signOut} style={styles.signOut}><AppText style={styles.signOutText}>გასვლა</AppText></Pressable></Screen>;
}
const styles = StyleSheet.create({ header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.lg }, eyebrow: { color: colors.rose, fontWeight: '800' }, title: { fontSize: 29, fontWeight: '800', marginTop: 2 }, photoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: spacing.lg }, photoSlot: { width: '31.8%', aspectRatio: 0.82, borderRadius: radius.md, overflow: 'hidden', backgroundColor: colors.roseSoft }, photo: { width: '100%', height: '100%', resizeMode: 'cover' }, add: { flex: 1, alignItems: 'center', justifyContent: 'center' }, delete: { position: 'absolute', right: 6, top: 6, width: 25, height: 25, borderRadius: 13, backgroundColor: 'rgba(0,0,0,0.58)', alignItems: 'center', justifyContent: 'center' }, info: { backgroundColor: colors.surface, borderRadius: radius.md, padding: spacing.md, marginBottom: spacing.md }, nameRow: { flexDirection: 'row', alignItems: 'center', gap: 7 }, profileName: { fontSize: 25, fontWeight: '800' }, profileAge: { fontSize: 22 }, muted: { color: colors.muted, marginTop: 5 }, bio: { fontSize: 15, lineHeight: 23, marginTop: 13 }, form: { gap: 12 }, input: { minHeight: 52, borderWidth: 1, borderColor: colors.line, borderRadius: radius.md, paddingHorizontal: 15, color: colors.ink, backgroundColor: colors.surface, fontSize: 16 }, bioInput: { minHeight: 110, textAlignVertical: 'top', paddingTop: 14 }, signOut: { alignItems: 'center', paddingVertical: 25 }, signOutText: { color: colors.rose, fontWeight: '700' } });
